INSERT INTO data_admin.validation_rule_registry (
    rule_id,
    class_code,
    field_name,
    rule_code,
    rule_label,
    severity,
    rule_type,
    reference_schema,
    reference_table,
    reference_column,
    sql_template,
    active,
    description
)
VALUES
(
    '10000000-0000-0000-0000-000000000001',
    'HYDRO_DEBIT',
    'station_id',
    'HYDRO_STATION_EXISTS',
    'Station hydrologique existante',
    'BLOCKING',
    'EXISTS_IN_REFERENCE',
    'infra',
    'stations_mesure',
    'id',
    NULL,
    true,
    'Le station_id fourni doit exister dans infra.stations_mesure.id.'
),
(
    '10000000-0000-0000-0000-000000000002',
    'HYDRO_DEBIT',
    NULL,
    'HYDRO_DUPLICATE_EXISTING',
    'Doublon potentiel hydro existant',
    'WARNING',
    'DUPLICATE_CHECK',
    'hydro',
    'mesure_debit',
    NULL,
    NULL,
    true,
    'Alerte si le triplet station_id + temps + valeur existe deja dans hydro.mesure_debit.'
),
(
    '10000000-0000-0000-0000-000000000003',
    'HYDRO_DEBIT',
    'valeur',
    'HYDRO_VALUE_REASONABLE_MAX',
    'Debit hors plage raisonnable',
    'WARNING',
    'RANGE_CHECK',
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    'Alerte si valeur depasse un seuil raisonnable de 5000 m3/s.'
),
(
    '10000000-0000-0000-0000-000000000004',
    'HYDRO_DEBIT',
    'temps',
    'HYDRO_TEMPS_NOT_FUTURE',
    'Horodatage futur hydro',
    'WARNING',
    'TEMPORAL_CHECK',
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    'Alerte si temps est dans le futur.'
),
(
    '10000000-0000-0000-0000-000000000005',
    'METEO_PRECIPITATION',
    'station_id',
    'METEO_STATION_EXISTS',
    'Station meteo existante',
    'BLOCKING',
    'EXISTS_IN_REFERENCE',
    'infra',
    'stations_mesure',
    'id',
    NULL,
    true,
    'Le station_id fourni doit exister dans infra.stations_mesure.id.'
),
(
    '10000000-0000-0000-0000-000000000006',
    'METEO_PRECIPITATION',
    NULL,
    'METEO_DUPLICATE_EXISTING',
    'Doublon potentiel meteo existant',
    'WARNING',
    'DUPLICATE_CHECK',
    'meteo',
    'mesure_precipitation',
    NULL,
    NULL,
    true,
    'Alerte si le couple station_id + temps existe deja dans meteo.mesure_precipitation.'
),
(
    '10000000-0000-0000-0000-000000000007',
    'METEO_PRECIPITATION',
    'val_observees',
    'METEO_VALUE_REASONABLE_MAX',
    'Precipitation hors plage raisonnable',
    'WARNING',
    'RANGE_CHECK',
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    'Alerte si val_observees depasse 500 mm.'
),
(
    '10000000-0000-0000-0000-000000000008',
    'METEO_PRECIPITATION',
    'temps',
    'METEO_TEMPS_NOT_FUTURE',
    'Horodatage futur meteo',
    'WARNING',
    'TEMPORAL_CHECK',
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    'Alerte si temps est dans le futur.'
),
(
    '10000000-0000-0000-0000-000000000009',
    'QUALITE_RIVIERE',
    'station_id',
    'QUALITE_STATION_EXISTS',
    'Station qualite existante',
    'BLOCKING',
    'EXISTS_IN_REFERENCE',
    'infra',
    'stations_mesure',
    'id',
    NULL,
    true,
    'Si station_id est renseigne, il doit exister dans infra.stations_mesure.id.'
),
(
    '10000000-0000-0000-0000-000000000010',
    'QUALITE_RIVIERE',
    'ire_station',
    'QUALITE_IRE_EXISTS',
    'Code station qualite existant',
    'BLOCKING',
    'EXISTS_IN_REFERENCE',
    'infra',
    'stations_mesure',
    'code_station',
    NULL,
    true,
    'Si ire_station est renseigne, il doit exister dans infra.stations_mesure.code_station.'
),
(
    '10000000-0000-0000-0000-000000000011',
    'QUALITE_RIVIERE',
    'parametre_qualite',
    'QUALITE_PARAM_EXISTS',
    'Parametre qualite canonique existant',
    'BLOCKING',
    'EXISTS_IN_REFERENCE',
    'metadata',
    'referentiel_parametre_canonique',
    'code_parametre',
    NULL,
    true,
    'Le parametre qualite doit exister et etre actif dans metadata.referentiel_parametre_canonique.'
),
(
    '10000000-0000-0000-0000-000000000012',
    'QUALITE_RIVIERE',
    NULL,
    'QUALITE_DUPLICATE_EXISTING',
    'Doublon potentiel qualite existant',
    'WARNING',
    'DUPLICATE_CHECK',
    'qualite',
    'mesure_qualite_riviere',
    NULL,
    NULL,
    true,
    'Alerte si station + temps + parametre existe deja dans qualite.mesure_qualite_riviere.'
),
(
    '10000000-0000-0000-0000-000000000013',
    'QUALITE_RIVIERE',
    'temps',
    'QUALITE_TEMPS_NOT_FUTURE',
    'Horodatage futur qualite',
    'WARNING',
    'TEMPORAL_CHECK',
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    'Alerte si temps est dans le futur.'
),
(
    '10000000-0000-0000-0000-000000000014',
    'INFRA_STATION',
    'code_station',
    'INFRA_STATION_CODE_UNIQUE',
    'Code station unique',
    'BLOCKING',
    'DUPLICATE_CHECK',
    'infra',
    'stations_mesure',
    'code_station',
    NULL,
    true,
    'Le code station ne doit pas exister dans infra.stations_mesure.'
),
(
    '10000000-0000-0000-0000-000000000015',
    'INFRA_STATION',
    'geom_wkt',
    'INFRA_GEOM_WKT_VALID',
    'Geometrie station valide',
    'BLOCKING',
    'CUSTOM_SQL',
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    'La geometrie WKT de la station doit etre parseable par PostGIS.'
),
(
    '10000000-0000-0000-0000-000000000016',
    'INFRA_STATION',
    'srid',
    'INFRA_SRID_ALLOWED',
    'SRID station autorise',
    'BLOCKING',
    'ALLOWED_VALUE_SQL',
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    'Le SRID de la station doit etre 4326 ou 26191.'
),
(
    '10000000-0000-0000-0000-000000000017',
    'INFRA_STATION',
    'geom_wkt',
    'INFRA_GEOM_NOT_EMPTY',
    'Geometrie station non vide',
    'BLOCKING',
    'CUSTOM_SQL',
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    'La geometrie station ne doit pas etre vide.'
),
(
    '10000000-0000-0000-0000-000000000018',
    'INFRA_STATION',
    'geom_wkt',
    'INFRA_GEOM_WITHIN_MOROCCO_BOUNDS',
    'Geometrie station dans les bornes Maroc',
    'BLOCKING',
    'CUSTOM_SQL',
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    'La geometrie station doit etre localisee dans les bornes Maroc.'
),
(
    '10000000-0000-0000-0000-000000000019',
    'POLLUTION_SITE',
    'site_code',
    'POLLUTION_SITE_CODE_UNIQUE',
    'Code site pollution unique',
    'BLOCKING',
    'DUPLICATE_CHECK',
    'geo',
    'ref_site_pollution',
    'site_code',
    NULL,
    true,
    'Le code site pollution ne doit pas exister dans geo.ref_site_pollution.'
),
(
    '10000000-0000-0000-0000-000000000020',
    'POLLUTION_SITE',
    'geom_wkt',
    'POLLUTION_GEOM_WKT_VALID',
    'Geometrie pollution valide',
    'BLOCKING',
    'CUSTOM_SQL',
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    'La geometrie WKT du site pollution doit etre parseable par PostGIS.'
),
(
    '10000000-0000-0000-0000-000000000021',
    'POLLUTION_SITE',
    'srid',
    'POLLUTION_SRID_ALLOWED',
    'SRID pollution autorise',
    'BLOCKING',
    'ALLOWED_VALUE_SQL',
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    'Le SRID du site pollution doit etre 4326 ou 26191.'
),
(
    '10000000-0000-0000-0000-000000000022',
    'POLLUTION_SITE',
    'geom_wkt',
    'POLLUTION_GEOM_NOT_EMPTY',
    'Geometrie pollution non vide',
    'BLOCKING',
    'CUSTOM_SQL',
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    'La geometrie du site pollution ne doit pas etre vide.'
),
(
    '10000000-0000-0000-0000-000000000023',
    'POLLUTION_SITE',
    'geom_wkt',
    'POLLUTION_GEOM_WITHIN_MOROCCO_BOUNDS',
    'Geometrie pollution dans les bornes Maroc',
    'BLOCKING',
    'CUSTOM_SQL',
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    'La geometrie du site pollution doit etre localisee dans les bornes Maroc.'
),
(
    '10000000-0000-0000-0000-000000000024',
    'POLLUTION_SITE',
    'geom_wkt',
    'POLLUTION_GEOMETRY_DUPLICATE_WARNING',
    'Doublon geometrique pollution',
    'WARNING',
    'DUPLICATE_CHECK',
    'geo',
    'ref_site_pollution',
    'geom_4326',
    NULL,
    true,
    'Alerte si la geometrie du site pollution existe deja a l''identique.'
)
ON CONFLICT (class_code, rule_code) DO UPDATE
SET
    field_name = EXCLUDED.field_name,
    rule_label = EXCLUDED.rule_label,
    severity = EXCLUDED.severity,
    rule_type = EXCLUDED.rule_type,
    reference_schema = EXCLUDED.reference_schema,
    reference_table = EXCLUDED.reference_table,
    reference_column = EXCLUDED.reference_column,
    sql_template = EXCLUDED.sql_template,
    active = EXCLUDED.active,
    description = EXCLUDED.description,
    updated_at = now();
